name: Lint

# Trigger this workflow manually, by pushing commits to any branch, or
# by filing a pull request.
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - id: cache-workdir
        uses: actions/cache@v3
        with:
          key: workdir-${{ github.sha }}
          path: .
      - if: steps.cache-workdir.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - run: python -m pip install .
      - uses: pre-commit/action@v3.0.0
