---
name: Release

# Trigger this workflow manually or after testing (main branch only).
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: release
        uses: python-semantic-release/python-semantic-release@v8.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache/save@v3
        with:
          path: .
          key: ${{ github.workflow }}-${{ github.ref }}-release
    outputs:
      released: ${{ steps.release.outputs.released }}
      tag: ${{ steps.release.outputs.tag }}

  build:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.released }} == 'true'
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ github.workflow }}-${{ github.ref }}-release
      - run: pip install build && python -m build
      - uses: actions/cache/save@v3
        with:
          path: .
          key: ${{ github.workflow }}-${{ github.ref }}-build

  testpypi:
    runs-on: ubuntu-latest
    needs:
      - release
      - build
    if: ${{ needs.release.outputs.released }} == 'true'
    environment:
      name: testpypi
      url: https://test.pypi.org/p/lethbridge
    permissions:
      id-token: write
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ github.workflow }}-${{ github.ref }}-build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          repository-url: https://test.pypi.org/legacy/
          verbose: true

  pypi:
    runs-on: ubuntu-latest
    needs:
      - release
      - build
      - testpypi
    if: ${{ needs.release.outputs.released }} == 'true'
    environment:
      name: pypi
      url: https://pypi.org/p/lethbridge
    permissions:
      id-token: write
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ github.workflow }}-${{ github.ref }}-build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          verbose: true

  github:
    runs-on: ubuntu-latest
    needs:
      - release
      - build
      - testpypi
    if: ${{ needs.release.outputs.released }} == 'true'
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ github.workflow }}-${{ github.ref }}-build
      - name: Publish package distributions to GitHub Releases
        uses: python-semantic-release/upload-to-gh-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.release.outputs.tag }}
